/* ui_state.mjs
 * All shared mutable state for SEQ8.
 * Import: import { S } from './ui_state.mjs';
 * Read: S.varName   Write: S.varName = v  or  S.arr[i] = v
 */

import {
    NUM_TRACKS, NUM_CLIPS, NUM_STEPS, DRUM_LANES, DRUM_BASE_NOTE
} from './ui_constants.mjs';

const PERF_FACTORY_PRESETS = [
    /* bits: 0=Oct↑ 1=Oct↓ 2=Sc↑ 3=Sc↓ 4=5th 5=Triton 6=Drift 7=Storm
             8=Soft 9=Hard 10=Cresc 11=Pulse 12=Sdchn 13=Stac 14=Lgto 15=RmpG
             16=½time 17=3Skip 18=Phnm 19=Sprs 20=Gltch 21=Stggr 22=Shfl 23=Back */
    { name: 'Float',    mods: (1<<2)|(1<<14) },           /* Sc↑ + Lgto */
    { name: 'Sink',     mods: (1<<1)|(1<<8)|(1<<13) },    /* Oct↓ + Decrsc + Stac */
    { name: 'Heartbt',  mods: (1<<11)|(1<<16) },          /* Pulse + ½time */
    { name: 'F.Dust',   mods: (1<<7)|(1<<9)|(1<<19) },    /* Storm + Swell + Sprs */
    { name: 'Robot',    mods: (1<<5)|(1<<11)|(1<<17) },   /* Triton + Pulse + 3Skip */
    { name: 'Dissolve', mods: (1<<6)|(1<<8)|(1<<18) },    /* Drift + Decrsc + Phnm */
    { name: 'Chaos',    mods: (1<<7)|(1<<20)|(1<<23) },   /* Storm + Gltch + Back */
    { name: 'Lift',     mods: (1<<2)|(1<<10)|(1<<15) },   /* Sc↑ + Cresc + RmpG */
];

const CC_ASSIGN_DEFAULTS = [7, 74, 71, 73, 72, 91, 93, 10];

export const S = {
    stubSwingAmt: 0,
    stubSwingRes: 0,
    inpQuant: false,
    midiInChannel: 0,
    beatMarkersEnabled: true,
    launchQuant: 0,
    scaleAware: 1,
    ledInitQueue: [],
    ledInitIndex: 0,
    ledInitComplete: false,
    shiftHeld: false,
    loopHeld: false,
    perfSync: true,
    perfStack: [],
    perfStickyLengths: new Set(),
    perfHoldPadHeld: false,
    perfModsToggled: 0,
    perfModsHeld: 0,
    perfLatchMode: false,
    perfLatchPressedTick: -1,
    perfSnapshots: PERF_FACTORY_PRESETS.map(function(p) { return p.mods; })
                           .concat(new Array(8).fill(0)),  /* slots 8-15 empty */
    perfRecalledSlot: -1,
    perfRecalledMods: 0,
    perfModPopupName: '',
    perfModPopupEndTick: -1,
    perfViewLocked: false,
    loopPressTick: -1,
    loopLastTapEndTick: -999,
    padKey: 9,
    padScale: 1,
    padOctave: new Array(NUM_TRACKS).fill(3),
    padNoteMap: new Array(32).fill(60),
    clipSteps: Array.from({length: NUM_TRACKS}, () =>
                           Array.from({length: NUM_CLIPS}, () => new Array(NUM_STEPS).fill(0))),
    clipNonEmpty: Array.from({length: NUM_TRACKS}, () => new Array(NUM_CLIPS).fill(false)),
    clipLength: Array.from({length: NUM_TRACKS}, () => new Array(NUM_CLIPS).fill(16)),
    clipTPS: Array.from({length: NUM_TRACKS}, () => new Array(NUM_CLIPS).fill(24)),
    clipSeqFollow: Array.from({length: NUM_TRACKS}, () => new Array(NUM_CLIPS).fill(true)),
    trackCurrentStep: new Array(NUM_TRACKS).fill(-1),
    trackCurrentPage: new Array(NUM_TRACKS).fill(0),
    activeDrumLane: new Array(NUM_TRACKS).fill(0),
    drumLanePage: new Array(NUM_TRACKS).fill(0),
    drumLaneSteps: Array.from({length: NUM_TRACKS}, () =>
    Array.from({length: DRUM_LANES}, () => new Array(256).fill('0'))),
    drumLaneHasNotes: Array.from({length: NUM_TRACKS}, () => new Array(DRUM_LANES).fill(false)),
    drumLaneNote: Array.from({length: NUM_TRACKS}, () =>
    Array.from({length: DRUM_LANES}, (_, l) => DRUM_BASE_NOTE + l)),
    drumLastVelZone: new Array(NUM_TRACKS).fill(12),
    drumLaneLength: new Array(NUM_TRACKS).fill(16),
    drumLaneTPS: new Array(NUM_TRACKS).fill(24),
    drumStepPage: new Array(NUM_TRACKS).fill(0),
    drumCurrentStep: new Array(NUM_TRACKS).fill(-1),
    drumLaneFlashTick: Array.from({length: NUM_TRACKS}, () => new Array(DRUM_LANES).fill(-999)),
    drumLaneMute: new Array(NUM_TRACKS).fill(0),
    drumLaneSolo: new Array(NUM_TRACKS).fill(0),
    drumLaneQnt: new Array(NUM_TRACKS).fill(0),
    drumPerformMode: new Array(NUM_TRACKS).fill(0),
    drumRepeatHeldPad: new Array(NUM_TRACKS).fill(-1),
    drumRepeatLatched: new Array(NUM_TRACKS).fill(false),
    pendingRepeatLane: -1,
    pendingRepeatLaneTrack: 0,
    drumRepeat2HeldLanes: Array.from({length: NUM_TRACKS}, () => new Set()),
    drumRepeat2LatchedLanes: Array.from({length: NUM_TRACKS}, () => new Set()),
    drumRepeat2RatePerLane: Array.from({length: NUM_TRACKS}, () => new Array(DRUM_LANES).fill(0)),
    rpt2LoopPadUsed: false,
    drumRepeatGate: Array.from({length: NUM_TRACKS}, () => new Array(DRUM_LANES).fill(0xFF)),
    drumRepeatVelScale: Array.from({length: NUM_TRACKS}, () =>
    Array.from({length: DRUM_LANES}, () => new Array(8).fill(100))),
    drumRepeatNudge: Array.from({length: NUM_TRACKS}, () =>
    Array.from({length: DRUM_LANES}, () => new Array(8).fill(0))),
    seqArpStepVel: Array.from({length: NUM_TRACKS}, () =>
    Array.from({length: NUM_CLIPS}, () => new Array(8).fill(4))),
    tarpStepVel: Array.from({length: NUM_TRACKS}, () => new Array(8).fill(4)),
    drumClipNonEmpty: Array.from({length: NUM_TRACKS}, () => new Array(NUM_CLIPS).fill(false)),
    trackActiveClip: new Array(NUM_TRACKS).fill(0),
    lastDspActiveClip: new Array(NUM_TRACKS).fill(0),
    trackQueuedClip: new Array(NUM_TRACKS).fill(-1),
    trackChannel: new Array(NUM_TRACKS).fill(1),
    trackRoute: new Array(NUM_TRACKS).fill(0),
    trackPadMode: new Array(NUM_TRACKS).fill(0),
    trackVelOverride: new Array(NUM_TRACKS).fill(0),
    trackLooper: new Array(NUM_TRACKS).fill(1),
    trackClipPlaying: new Array(NUM_TRACKS).fill(false),
    trackWillRelaunch: new Array(NUM_TRACKS).fill(false),
    trackPendingPageStop: new Array(NUM_TRACKS).fill(false),
    sceneBtnFlashTick: new Array(4).fill(-1),
    playing: false,
    activeTrack: 0,
    sessionView: false,
    hasInitedOnce: false,
    sceneRow: 0,
    flashEighth: false,
    flashSixteenth: false,
    masterPos: 0,
    dspLooperState: 0,
    dspMergeState: 0,
    dspMergeDstClip: 0,
    dspMergeTrack: -1,
    pendingMergeArm: false,
    pendingBankRefresh: -1,
    tickCount: 0,
    cachedSceneAllPlaying: new Array(16).fill(false),
    cachedSceneAllQueued: new Array(16).fill(false),
    cachedSceneAnyPlaying: new Array(16).fill(false),
    activeBank: 0,
    knobTouched: -1,
    knobAccum: new Array(8).fill(0),
    knobLastDir: new Array(8).fill(0),
    knobLocked: new Array(8).fill(false),
    knobTurnedTick: new Array(8).fill(-1),
    bankSelectTick: -1,
    jogTouched: false,
    stretchBlockedEndTick: -1,
    noNoteFlashEndTick: -1,
    trackOctave: new Array(NUM_TRACKS).fill(0),
    actionPopupEndTick: -1,
    actionPopupLines: [],
    actionPopupHighlight: -1,
    clockShiftTouchDelta: 0,
    screenDirty: true,
    lastBlinkOn: null,
    bankParams: Array.from({length: NUM_TRACKS}, () =>
    BANKS.map(bank => bank.knobs.map(k => k.def))),
    trackCCAssign: Array.from({length: NUM_TRACKS}, () => CC_ASSIGN_DEFAULTS.slice()),
    trackCCVal: Array.from({length: NUM_TRACKS}, () => new Array(8).fill(0)),
    trackCCAutoBits: Array.from({length: NUM_TRACKS}, () => new Array(NUM_CLIPS).fill(0)),
    trackCCLiveVal: Array.from({length: NUM_TRACKS}, () => new Array(8).fill(-1)),
    heldStepBtn: -1,
    heldStep: -1,
    heldStepNotes: [],
    stepWasEmpty: false,
    stepWasHeld: false,
    stepEditVel: 100,
    stepEditGate: 12,
    stepEditNudge: 0,
    ccStepEditVal: new Array(8).fill(0),
    ccStepEditActive: false,
    ccPaletteCache: new Array(8).fill(-1),
    ccPaletteCacheArmed: false,
    ccPaletteCacheTrack: -1,
    stepBtnPressedTick: new Array(16).fill(-1),
    lastPlayedNote: -1,
    lastPadVelocity: 100,
    liveActiveNotes: new Set(),
    seqActiveNotes: new Set(),
    seqLastStep: -1,
    seqLastClip: -1,
    seqNoteOnClipTick: -1,
    seqNoteGateTicks: 0,
    deleteHeld: false,
    muteHeld: false,
    muteUsedAsModifier: false,
    metronomeOn: 1,
    metronomeOnLast: 1,
    metronomeVol: 100,
    metroPrevBeat: 0,
    metroNoteOffTick: -1,
    copyHeld: false,
    copySrc: null,
    lastSoloBlink: null,
    undoAvailable: false,
    redoAvailable: false,
    undoSeqArpSnapshot: null,
    redoSeqArpSnapshot: null,
    trackMuted: new Array(NUM_TRACKS).fill(false),
    trackSoloed: new Array(NUM_TRACKS).fill(false),
    snapshots: new Array(16).fill(null),
    _origClearScreen: null,
    _wasSuspended: false,
    globalMenuOpen: false,
    globalMenuItems: null,
    globalMenuState: null,
    globalMenuStack: null,
    bpmWasEditing: false,
    lastSentMenuEditValue: null,
    confirmClearSession: false,
    confirmBake: false,
    confirmBakeSel: 1,
    confirmBakeIsDrum: false,
    confirmBakeTrack: 0,
    confirmBakeClip: 0,
    tapTempoOpen: false,
    tapTempoTapTimes: [],
    tapTempoBpm: 120,
    tapTempoFlashTick: -1,
    tapTempoFlashPad: -1,
    confirmClearSel: 1,
    noteSessionPressedTick: -1,
    sessionOverlayHeld: false,
    overviewCache: null,
    recordArmed: false,
    recordCountingIn: false,
    recordArmedTrack: -1,
    countInStartTick: -1,
    countInQuarterTicks: 0,
    countInDspPrev: false,
    playingPrev: false,
    _recNoteOns: [],
    _recNoteOffs: [],
    recordBpm: 120,
    currentSetUuid: '',
    lastDspInstanceId: '',
    stepOpTick: -99,
    pendingSetLoad: false,
    pendingDspSync: 0,
    pendingUndoSync: 0,
    pendingDefaultSetParams: [],
    uiDefaultsApplyAfterSync: false,
    pendingStepsReread: 0,
    pendingStepsRereadTrack: 0,
    pendingStepsRereadClip: 0,
    pendingDrumResync: 0,
    pendingDrumResyncTrack: 0,
    pendingDrumLaneResync: 0,
    pendingDrumLaneResyncTrack: 0,
    pendingDrumLaneResyncLane: 0,

};
